texto = input('Digite algo: ')
print('O seu tipo primitivo e ', type(texto))
print('So tem so espaço? ',texto.isspace())
print('E um numero? ',texto.isnumeric())
print('E alfabetico? ', texto.isalpha())
print('E afanumerico? ', texto.isalnum())
print('Esta em maiusculo? ', texto.isupper())
print('Esta em minusculo? ', texto.islower())
print('Esta em capitalizada?', texto.istitle())